### ISSUE TITLE
Détruire la liste d'indices aléatoires à la fin de l'algo

### ISSUE THREAD

**Issue by lemairecarl** [atompacman/IMN430-TP3-ConvexHull3D#2]
@atompacman Est-ce que le la liste d'indices (`int* index`) va être `delete` automatiquement à la fin de `compute3DConvexHull`?

**Comment by atompacman** [comment]
Zone en construction. J'voulais pas nécessairement tout mettre dans master parce qu'il y a des choses en cours qui ne font pas beaucoup de sens encore pour l'instant.

**Comment by lemairecarl** [comment]
Ok

Envoyé de mon iPhone
